apiVersion: apps/v1
kind: Deployment
metadata:
  name: 981-auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: wajidali05/auth:latest
        ports:
        - containerPort: 4000
